# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Will Nye
email: wnye71@googlemail.com
description: The SEO guy.
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wnye71.github.io" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'Will Nye'
bio: >
  Mea suas vituperatoribus et, virtute corpora quaestio cum ut.
  Dfkfk
author_image: "/assets/images/author.jpg"
twitter_username: williamjnye
github_username:  wnye71

# Google Analytics
analytics_id: "58543053"

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
